version: "1"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hive-namenode:/hadoop/dfs/name
    env_file:
      - ./hive/hadoop-hive.env
    environment:
      - CLUSTER_NAME=tubo
    ports:
      - "50070:50070"
    networks:
      - tubo-database-net
  
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hive-datanode:/hadoop/dfs/data
    env_file:
      - ./hive/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    ports:
      - "50075:50075"
    networks:
      - tubo-database-net
  
  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    env_file:
      - ./hive/hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - tubo-database-net
  
  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hive/hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    command: /opt/hive/bin/hive --service metastore    
    ports:
      - "59083:9083"
    networks:
      - tubo-database-net
  
  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    ports:
      - "25432:5432"
    networks:
      - tubo-database-net
  presto:
    image: prestodb/presto:latest  
    container_name: presto
    ports:
      - "28080:8080"
    volumes:
      - ./presto/config.properties:/opt/presto-server/etc/config.properties
      - ./presto/jvm.config:/opt/presto-server/etc/jvm.config
      - ./presto/core-site.xml:/etc/hadoop/core-site.xml
      - ./presto/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
      - ./presto/tpch.properties:/opt/presto-server/etc/catalog/tpch.properties
      - ./presto/hive.properties:/opt/presto-server/etc/catalog/hive.properties
    networks:
      - tubo-database-net

volumes:
  hive-namenode:
    name: hive-namenode
  hive-datanode:
    name: hive-datanode
  

networks:
  tubo-database-net:
    driver: bridge
    name: tubo-database-net
    external: true
    
