CREATE USER marmot IDENTIFIED BY "ilvTD!@#";
GRANT CONNECT, RESOURCE TO marmot;
ALTER USER marmot QUOTA UNLIMITED ON USERS;


-- MARMOT."A8_2022_Sales_Targets_for_Each_Store.csv" definition

CREATE TABLE "MARMOT"."A8_2022_Sales_Targets_for_Each_Store.csv" 
   (	"`Store Number`" NUMBER(*,0), 
	"` Sales Target`" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- MARMOT."A8_2022_Store_Foot_Traffic.csv" definition

CREATE TABLE "MARMOT"."A8_2022_Store_Foot_Traffic.csv" 
   (	"`Date`" VARCHAR2(50), 
	"`Store Number`" NUMBER(*,0), 
	"`Foot Traffic`" NUMBER(*,0), 
	"`Number of Visitors`" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- MARMOT.A8_DAILY_SALES_DETAILS definition

CREATE TABLE "MARMOT"."A8_DAILY_SALES_DETAILS" 
   (	"`Date`" VARCHAR2(50), 
	"`Product Category`" VARCHAR2(50), 
	"`Store Number`" NUMBER(*,0), 
	"`Daily Sales`" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- MARMOT.A8_STORE_LIST definition

CREATE TABLE "MARMOT"."A8_STORE_LIST" 
   (	"`Store Number`" NUMBER(*,0), 
	"`Store Name`" VARCHAR2(50), 
	"City" VARCHAR2(50), 
	"Province" VARCHAR2(50)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;